# Generated by Django 4.2.4 on 2023-08-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_xid', models.CharField(max_length=100, unique=True)),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
