# Generated by Django 4.2.4 on 2023-08-10 03:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userwallet_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
