# Generated by Django 4.2.4 on 2023-08-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userwallet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='balance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='enabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
