# Generated by Django 4.2.4 on 2023-08-10 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userwallet_balance_userwallet_enabled_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwallet',
            name='active',
        ),
        migrations.AddField(
            model_name='userwallet',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'enabled'), (2, 'disabled')], null=True),
        ),
    ]
