# Generated by Django 4.2.4 on 2023-08-10 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_userwallet_active_userwallet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'enabled'), (2, 'disabled')], default=2, null=True),
        ),
    ]
