# Generated by Django 4.2.4 on 2023-08-10 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userwallet_disanled_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'deposit'), (2, 'withdraw')], null=True)),
                ('amount', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userwallet')),
            ],
        ),
    ]
