# Generated by Django 4.2.4 on 2023-08-10 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_idempotenttable_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userwallet',
            old_name='disanled_at',
            new_name='disabled_at',
        ),
    ]
